// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_rray_RCPPEXPORTS_H_GEN_
#define RCPP_rray_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace rray {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("rray", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("rray", "_rray_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in rray");
            }
        }
    }

    inline Rcpp::IntegerVector rray_dim(Rcpp::RObject x) {
        typedef SEXP(*Ptr_rray_dim)(SEXP);
        static Ptr_rray_dim p_rray_dim = NULL;
        if (p_rray_dim == NULL) {
            validateSignature("Rcpp::IntegerVector(*rray_dim)(Rcpp::RObject)");
            p_rray_dim = (Ptr_rray_dim)R_GetCCallable("rray", "_rray_rray_dim");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rray_dim(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

}

#endif // RCPP_rray_RCPPEXPORTS_H_GEN_
