# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mtrx_add_cpp <- function(x, y) {
    .Call(`_mtrx_mtrx_add_cpp`, x, y)
}

mtrx_subtract_cpp <- function(x, y) {
    .Call(`_mtrx_mtrx_subtract_cpp`, x, y)
}

mtrx_multiply_cpp <- function(x, y) {
    .Call(`_mtrx_mtrx_multiply_cpp`, x, y)
}

mtrx_divide_cpp <- function(x, y) {
    .Call(`_mtrx_mtrx_divide_cpp`, x, y)
}

