# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rray__add <- function(x, y) {
    .Call(`_rray_rray__add`, x, y)
}

rray__subtract <- function(x, y) {
    .Call(`_rray_rray__subtract`, x, y)
}

rray__divide <- function(x, y) {
    .Call(`_rray_rray__divide`, x, y)
}

rray__multiply <- function(x, y) {
    .Call(`_rray_rray__multiply`, x, y)
}

rray__pow <- function(x, y) {
    .Call(`_rray_rray__pow`, x, y)
}

rray__identity <- function(x) {
    .Call(`_rray_rray__identity`, x)
}

rray__opposite <- function(x) {
    .Call(`_rray_rray__opposite`, x)
}

rray__bind <- function(proxy, args, axis) {
    .Call(`_rray_rray__bind`, proxy, args, axis)
}

rray__broadcast <- function(x, dim) {
    .Call(`_rray_rray__broadcast`, x, dim)
}

rray__full_like <- function(x, value) {
    .Call(`_rray_rray__full_like`, x, value)
}

rray__diag <- function(x, offset) {
    .Call(`_rray_rray__diag`, x, offset)
}

vec__cast_inner <- function(x, to) {
    .Call(`_rray_vec__cast_inner`, x, to)
}

rray__greater <- function(x, y) {
    .Call(`_rray_rray__greater`, x, y)
}

rray__greater_equal <- function(x, y) {
    .Call(`_rray_rray__greater_equal`, x, y)
}

rray__lesser <- function(x, y) {
    .Call(`_rray_rray__lesser`, x, y)
}

rray__lesser_equal <- function(x, y) {
    .Call(`_rray_rray__lesser_equal`, x, y)
}

rray__equal <- function(x, y) {
    .Call(`_rray_rray__equal`, x, y)
}

rray__not_equal <- function(x, y) {
    .Call(`_rray_rray__not_equal`, x, y)
}

rray__all_equal <- function(x, y) {
    .Call(`_rray_rray__all_equal`, x, y)
}

rray__any_not_equal <- function(x, y) {
    .Call(`_rray_rray__any_not_equal`, x, y)
}

rray__resize_dim_names <- function(dim_names, dim) {
    .Call(`_rray_rray__resize_dim_names`, dim_names, dim)
}

rray__coalesce_meta_dim_names <- function(x_meta_dim_names, y_meta_dim_names) {
    .Call(`_rray_rray__coalesce_meta_dim_names`, x_meta_dim_names, y_meta_dim_names)
}

rray__coalesce_dim_names <- function(x_dim_names, y_dim_names) {
    .Call(`_rray_rray__coalesce_dim_names`, x_dim_names, y_dim_names)
}

rray__dim_names2 <- function(x, y) {
    .Call(`_rray_rray__dim_names2`, x, y)
}

rray__new_empty_dim_names <- function(n) {
    .Call(`_rray_rray__new_empty_dim_names`, n)
}

rray__dim_names <- function(x) {
    .Call(`_rray_rray__dim_names`, x)
}

rray__dim <- function(x) {
    .Call(`_rray_rray__dim`, x)
}

rray__dim2 <- function(x_dim, y_dim) {
    .Call(`_rray_rray__dim2`, x_dim, y_dim)
}

rray__dims <- function(x) {
    .Call(`_rray_rray__dims`, x)
}

rray__increase_dims <- function(dim, dims) {
    .Call(`_rray_rray__increase_dims`, dim, dims)
}

rray__extract_assign <- function(x, indexer, value) {
    .Call(`_rray_rray__extract_assign`, x, indexer, value)
}

rray__extract <- function(x, indexer) {
    .Call(`_rray_rray__extract`, x, indexer)
}

rray__reshape <- function(x, dim) {
    .Call(`_rray_rray__reshape`, x, dim)
}

rray_init <- function(ns) {
    .Call(`_rray_rray_init`, ns)
}

rray__logical_and <- function(x, y) {
    .Call(`_rray_rray__logical_and`, x, y)
}

rray__logical_or <- function(x, y) {
    .Call(`_rray_rray__logical_or`, x, y)
}

rray__logical_not <- function(x) {
    .Call(`_rray_rray__logical_not`, x)
}

rray__any <- function(x, axes) {
    .Call(`_rray_rray__any`, x, axes)
}

rray__all <- function(x, axes) {
    .Call(`_rray_rray__all`, x, axes)
}

rray__if_else <- function(condition, true_, false_) {
    .Call(`_rray_rray__if_else`, condition, true_, false_)
}

rray__split <- function(x, axes) {
    .Call(`_rray_rray__split`, x, axes)
}

rray__rotate <- function(x, from, to, times) {
    .Call(`_rray_rray__rotate`, x, from, to, times)
}

rray__transpose <- function(x, permutation) {
    .Call(`_rray_rray__transpose`, x, permutation)
}

rray__squeeze <- function(x, axes) {
    .Call(`_rray_rray__squeeze`, x, axes)
}

rray__expand_dims <- function(x, axis) {
    .Call(`_rray_rray__expand_dims`, x, axis)
}

rray__flip <- function(x, axis) {
    .Call(`_rray_rray__flip`, x, axis)
}

rray__flatten <- function(x) {
    .Call(`_rray_rray__flatten`, x)
}

rray__multiply_add <- function(x, y, z) {
    .Call(`_rray_rray__multiply_add`, x, y, z)
}

rray__abs <- function(x) {
    .Call(`_rray_rray__abs`, x)
}

rray__sign <- function(x) {
    .Call(`_rray_rray__sign`, x)
}

rray__fmod <- function(x, y) {
    .Call(`_rray_rray__fmod`, x, y)
}

rray__remainder <- function(x, y) {
    .Call(`_rray_rray__remainder`, x, y)
}

rray__maximum <- function(x, y) {
    .Call(`_rray_rray__maximum`, x, y)
}

rray__minimum <- function(x, y) {
    .Call(`_rray_rray__minimum`, x, y)
}

rray__clip <- function(x, low, high) {
    .Call(`_rray_rray__clip`, x, low, high)
}

rray__erf <- function(x) {
    .Call(`_rray_rray__erf`, x)
}

rray__erfc <- function(x) {
    .Call(`_rray_rray__erfc`, x)
}

rray__gamma <- function(x) {
    .Call(`_rray_rray__gamma`, x)
}

rray__lgamma <- function(x) {
    .Call(`_rray_rray__lgamma`, x)
}

rray__exp <- function(x) {
    .Call(`_rray_rray__exp`, x)
}

rray__exp2 <- function(x) {
    .Call(`_rray_rray__exp2`, x)
}

rray__expm1 <- function(x) {
    .Call(`_rray_rray__expm1`, x)
}

rray__log <- function(x, base) {
    .Call(`_rray_rray__log`, x, base)
}

rray__log2 <- function(x) {
    .Call(`_rray_rray__log2`, x)
}

rray__log10 <- function(x) {
    .Call(`_rray_rray__log10`, x)
}

rray__log1p <- function(x) {
    .Call(`_rray_rray__log1p`, x)
}

rray__sinh <- function(x) {
    .Call(`_rray_rray__sinh`, x)
}

rray__cosh <- function(x) {
    .Call(`_rray_rray__cosh`, x)
}

rray__tanh <- function(x) {
    .Call(`_rray_rray__tanh`, x)
}

rray__asinh <- function(x) {
    .Call(`_rray_rray__asinh`, x)
}

rray__acosh <- function(x) {
    .Call(`_rray_rray__acosh`, x)
}

rray__atanh <- function(x) {
    .Call(`_rray_rray__atanh`, x)
}

rray__ceiling <- function(x) {
    .Call(`_rray_rray__ceiling`, x)
}

rray__floor <- function(x) {
    .Call(`_rray_rray__floor`, x)
}

rray__trunc <- function(x) {
    .Call(`_rray_rray__trunc`, x)
}

rray__square <- function(x) {
    .Call(`_rray_rray__square`, x)
}

rray__cube <- function(x) {
    .Call(`_rray_rray__cube`, x)
}

rray__sqrt <- function(x) {
    .Call(`_rray_rray__sqrt`, x)
}

rray__cbrt <- function(x) {
    .Call(`_rray_rray__cbrt`, x)
}

rray__hypot <- function(x, y) {
    .Call(`_rray_rray__hypot`, x, y)
}

rray__sin <- function(x) {
    .Call(`_rray_rray__sin`, x)
}

rray__cos <- function(x) {
    .Call(`_rray_rray__cos`, x)
}

rray__tan <- function(x) {
    .Call(`_rray_rray__tan`, x)
}

rray__asin <- function(x) {
    .Call(`_rray_rray__asin`, x)
}

rray__acos <- function(x) {
    .Call(`_rray_rray__acos`, x)
}

rray__atan <- function(x) {
    .Call(`_rray_rray__atan`, x)
}

rray__atan2 <- function(y, x) {
    .Call(`_rray_rray__atan2`, y, x)
}

rray__sort <- function(x, axis) {
    .Call(`_rray_rray__sort`, x, axis)
}

rray__max_pos <- function(x, axis) {
    .Call(`_rray_rray__max_pos`, x, axis)
}

rray__min_pos <- function(x, axis) {
    .Call(`_rray_rray__min_pos`, x, axis)
}

rray__sum <- function(x, axes) {
    .Call(`_rray_rray__sum`, x, axes)
}

rray__prod <- function(x, axes) {
    .Call(`_rray_rray__prod`, x, axes)
}

rray__mean <- function(x, axes) {
    .Call(`_rray_rray__mean`, x, axes)
}

rray__max <- function(x, axes) {
    .Call(`_rray_rray__max`, x, axes)
}

rray__min <- function(x, axes) {
    .Call(`_rray_rray__min`, x, axes)
}

rray__subset_assign <- function(x, indexer, value) {
    .Call(`_rray_rray__subset_assign`, x, indexer, value)
}

is_any_na_int <- function(x) {
    .Call(`_rray_is_any_na_int`, x)
}

is_contiguous_increasing <- function(x) {
    .Call(`_rray_is_contiguous_increasing`, x)
}

subset_dim_names <- function(dim_names, indexer) {
    .Call(`_rray_subset_dim_names`, dim_names, indexer)
}

rray__subset <- function(x, indexer) {
    .Call(`_rray_rray__subset`, x, indexer)
}

vec__type_inner2 <- function(x, y) {
    .Call(`_rray_vec__type_inner2`, x, y)
}

rray__validate_dim <- function(dim) {
    invisible(.Call(`_rray_rray__validate_dim`, dim))
}

rray__validate_reshape <- function(x, dim) {
    invisible(.Call(`_rray_rray__validate_reshape`, x, dim))
}

rray__validate_broadcastable_to_dim <- function(x_dim, dim) {
    invisible(.Call(`_rray_rray__validate_broadcastable_to_dim`, x_dim, dim))
}

rray__yank_assign <- function(x, i, value) {
    .Call(`_rray_rray__yank_assign`, x, i, value)
}

rray__yank <- function(x, i) {
    .Call(`_rray_rray__yank`, x, i)
}

