# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mtrx_add <- function(x, y) {
    .Call(`_mtrx_mtrx_add`, x, y)
}

mtrx_subtract <- function(x, y) {
    .Call(`_mtrx_mtrx_subtract`, x, y)
}

mtrx_multiply <- function(x, y) {
    .Call(`_mtrx_mtrx_multiply`, x, y)
}

mtrx_divide <- function(x, y) {
    .Call(`_mtrx_mtrx_divide`, x, y)
}

